plugins:
  - jekyll-relative-links
  - jekyll-readme-index

relative_links:
  enabled: true
  collections: true
include:
  - Letter/**
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-architect
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
